// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: TESTFN4

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_HomeScreen
void ui_HomeScreen_screen_init(void);
lv_obj_t * ui_HomeScreen;
lv_obj_t * ui_DateHome;
lv_obj_t * ui_DayOTWHome;
lv_obj_t * ui_DayHome;
lv_obj_t * ui_MonthNameHome;
lv_obj_t * ui_YearHome;
lv_obj_t * ui_HourHome;
lv_obj_t * ui_colon1;
lv_obj_t * ui_MinuteHome;
lv_obj_t * ui_SecondHome;
lv_obj_t * ui_colon2;
lv_obj_t * ui_SunHome;
lv_obj_t * ui_CloudHome;
void ui_event_BtnMenu(lv_event_t * e);
lv_obj_t * ui_BtnMenu;
lv_obj_t * ui_ImgBtnMenu;
///
lv_obj_t * ui_namedayweather;
lv_obj_t * ui_iconweather;
lv_obj_t * ui_tempminweather;
lv_obj_t * ui_tempminweather1;
lv_obj_t * ui_tempmaxweather;
lv_obj_t * ui_tempmaxweather1;
lv_obj_t * ui_humweather;
lv_obj_t * ui_humweather1;
lv_obj_t * ui_pressureweather;
lv_obj_t * ui_pressureweather1;
lv_obj_t * ui_windspeedweather;
lv_obj_t * ui_windspeedweather1;
lv_obj_t * ui_iconweather1;
lv_obj_t * ui_iconweather2;
lv_obj_t * ui_iconweather3;
lv_obj_t * ui_PnDCN1;
lv_obj_t * ui_Connect1;
lv_obj_t * ui_PnDCN2;
lv_obj_t * ui_Connect2;
lv_obj_t * ui_PnDCN3;
lv_obj_t * ui_Connect3;
///

// SCREEN: ui_LoginScreen
void ui_LoginScreen_screen_init(void);
lv_obj_t * ui_LoginScreen;
void ui_event_PinCodeTextArea(lv_event_t * e);
lv_obj_t * ui_PinCodeTextArea;
lv_obj_t * ui_TitleLogin;
void ui_event_LoginButton(lv_event_t * e);
lv_obj_t * ui_LoginButton;
lv_obj_t * ui_LoginText;
lv_obj_t * ui_LOGINFAILED;
lv_obj_t * ui_SENDNEWPW;
void ui_event_TextForgotPWUserLogin(lv_event_t * e);
lv_obj_t * ui_TextForgotPWUserLogin;
void ui_event_KBLogin(lv_event_t * e);
lv_obj_t * ui_KBLogin;

// SCREEN: ui_MenuScreen
void ui_MenuScreen_screen_init(void);
lv_obj_t * ui_MenuScreen;
lv_obj_t * ui_TitleMenu;
void ui_event_BTNExitMN(lv_event_t * e);
lv_obj_t * ui_BTNExitMN;
lv_obj_t * ui_IcExitMenu;
lv_obj_t * ui_TextBTNExit;
void ui_event_BTNSettingUser(lv_event_t * e);
lv_obj_t * ui_BTNSettingUser;
lv_obj_t * ui_IcSTuserMenu;
lv_obj_t * ui_TextBTNSTuser1;
void ui_event_BTNRoom(lv_event_t * e);
lv_obj_t * ui_BTNRoom;
lv_obj_t * ui_IcRoomMenu;
lv_obj_t * ui_TextBTNRoom;
void ui_event_BTNSettingTime(lv_event_t * e);
lv_obj_t * ui_BTNSettingTime;
lv_obj_t * ui_IcSTTimeMenu;
lv_obj_t * ui_TextBTNSTTime1;


// SCREEN: ui_SettingUserScreen
void ui_SettingUserScreen_screen_init(void);
lv_obj_t * ui_SettingUserScreen;
lv_obj_t * ui_TitleSettingUser;
lv_obj_t * ui_TitleEditPW;
void ui_event_TextCurrentPW(lv_event_t * e);
lv_obj_t * ui_TextCurrentPW;
void ui_event_TextNewPW(lv_event_t * e);
lv_obj_t * ui_TextNewPW;
//lv_obj_t * ui_TextForgotPW;
void ui_event_BTNSaveChangeSTUser(lv_event_t * e);
lv_obj_t * ui_BTNSaveChangeSTUser;
lv_obj_t * ui_TextBTNSaveChangeSTUser;
void ui_event_KBSetPW(lv_event_t * e);
lv_obj_t * ui_KBSetPW;
lv_obj_t * ui_NotifySuccsess;
lv_obj_t * ui_TextWrongPW;


// SCREEN: ui_SettingTimeScreen
void ui_SettingTimeScreen_screen_init(void);
lv_obj_t * ui_SettingTimeScreen;
lv_obj_t * ui_TitleSettingTime;
lv_obj_t * ui_TextSetYearr;
void ui_event_TextSetYear(lv_event_t * e);
lv_obj_t * ui_TextSetYear;
lv_obj_t * ui_GRSetDate;
lv_obj_t * ui_BGSetDate;
lv_obj_t * ui_RLSetDate;
lv_obj_t * ui_TextSetDate;
lv_obj_t * ui_GRSetMonth;
lv_obj_t * ui_BGSetMonth;
lv_obj_t * ui_RLSetMonth;
lv_obj_t * ui_TextSetMonth;
lv_obj_t * ui_GRSetHour;
lv_obj_t * ui_BGSetHour;
lv_obj_t * ui_RLSetHour;
lv_obj_t * ui_TextSetHour;
lv_obj_t * ui_GRSetMinute;
lv_obj_t * ui_BGSetMinute;
lv_obj_t * ui_RLSetMinute;
lv_obj_t * ui_TextSetMinute;
void ui_event_BTNBackToMenuSTTime(lv_event_t * e);
lv_obj_t * ui_BTNBackToMenuSTTime;
lv_obj_t * ui_TextBTNBackToMenuSTTime;
void ui_event_BTNBackToMenuSTTime1(lv_event_t * e);
lv_obj_t * ui_BTNBackToMenuSTTime1;
lv_obj_t * ui_TextBTNBackToMenuSTTime1;
void ui_event_KeyboardSetYear(lv_event_t * e);
lv_obj_t * ui_KeyboardSetYear;


// SCREEN: ui_LivingRoomScreen
void ui_LivingRoomScreen_screen_init(void);
void ui_event_LivingRoomScreen(lv_event_t * e);
lv_obj_t * ui_LivingRoomScreen;
lv_obj_t * ui_TextTitleLVRoom;
lv_obj_t * ui_TextAutoLVR;
void ui_event_SwitchAuto(lv_event_t * e);
lv_obj_t * ui_SwitchAuto;
lv_obj_t * ui_ValueAndStatusLVR;
lv_obj_t * ui_TextTempLVR;
lv_obj_t * ui_ValTempLVR;
lv_obj_t * ui_CelsiusTempLVR;
lv_obj_t * ui_TextHumLVR;
lv_obj_t * ui_ValHumLVR;
lv_obj_t * ui_PercentHumLVR;
lv_obj_t * ui_TextCO2LVR;
lv_obj_t * ui_ValCO2LVR;
lv_obj_t * ui_PPMCO2LVR;
lv_obj_t * ui_TextTVOCLVR;
lv_obj_t * ui_ValTVOCLVR;
lv_obj_t * ui_PPBTVOCLVR;
lv_obj_t * ui_TextFireSSLVR;
lv_obj_t * ui_ValFireSSLVR;
lv_obj_t * ui_TextSmokeSSLVR;
lv_obj_t * ui_ValSmokeSSLVR;
lv_obj_t * ui_TextDevice1LVR;
void ui_event_SwitchDevice1LVR(lv_event_t * e);
lv_obj_t * ui_SwitchDevice1LVR;
lv_obj_t * ui_TextDevice2LVR;
void ui_event_SwitchDevice2LVR(lv_event_t * e);
lv_obj_t * ui_SwitchDevice2LVR;
void ui_event_BTNBackToMenuLVR(lv_event_t * e);
lv_obj_t * ui_BTNBackToMenuLVR;
lv_obj_t * ui_TextBTNBackToMenuLVR;


// SCREEN: ui_KitchenRoomScreen
void ui_KitchenRoomScreen_screen_init(void);
void ui_event_KitchenRoomScreen(lv_event_t * e);
lv_obj_t * ui_KitchenRoomScreen;
void ui_event_BTNBackToMenuKCR(lv_event_t * e);
lv_obj_t * ui_BTNBackToMenuKCR;
lv_obj_t * ui_TextBTNBackToMenuKCR;
lv_obj_t * ui_TextTitleKCRoom;


// SCREEN: ui_FarmScreen
void ui_FarmScreen_screen_init(void);
void ui_event_FarmScreen(lv_event_t * e);
lv_obj_t * ui_FarmScreen;
lv_obj_t * ui_TextTitleFarm;
lv_obj_t * ui_ValueAndStatusFarm;
lv_obj_t * ui_TextTempFarm;
lv_obj_t * ui_ValTempFarm;
lv_obj_t * ui_CelsiusTempFarm;
lv_obj_t * ui_TextHumFarm;
lv_obj_t * ui_ValHumFarm;
lv_obj_t * ui_PercentHumFarm;
lv_obj_t * ui_TextSoilFarm;
lv_obj_t * ui_ValSoilFarm;
lv_obj_t * ui_PercentSoilFarm;
lv_obj_t * ui_TextRainSSFarm;
lv_obj_t * ui_ValRainSSFarm;
lv_obj_t * ui_TextDeviceFarm;
void ui_event_SwitchDevice1FARM(lv_event_t * e);
lv_obj_t * ui_SwitchDevice1FARM;
lv_obj_t * ui_LabelTimerFarm;
void ui_event_SwitchDevice2FARM(lv_event_t * e);
lv_obj_t * ui_SwitchDevice2FARM;
lv_obj_t * ui_TimerFarm;
lv_obj_t * ui_TextTimerFarm;
lv_obj_t * ui_TextNotifTimerFarm;
lv_obj_t * ui_BGSetHourTimerFarm;
lv_obj_t * ui_TextSetHourTimerFarm;
lv_obj_t * ui_RLSetHourTimerFarm;
lv_obj_t * ui_TextSetMinuteTimerFarm;
lv_obj_t * ui_BGSetMinuteTimerFarm;
lv_obj_t * ui_RLSetMinuteTimerFarm;
void ui_event_BtnTimerFarm(lv_event_t * e);
lv_obj_t * ui_BtnTimerFarm;
lv_obj_t * ui_TextBTNTimerFarm;
void ui_event_BTNBackToMenuFarm(lv_event_t * e);
lv_obj_t * ui_BTNBackToMenuFarm;
lv_obj_t * ui_TextBTNBackToMenuFarm;
lv_obj_t * ui____initial_actions0;
const lv_img_dsc_t * ui_imgset_bg[2] = {&ui_img_bg2_png, &ui_img_bg3_png};
const lv_img_dsc_t * ui_imgset_bggg[1] = {&ui_img_bggg2_png};
const lv_img_dsc_t * ui_imgset_bgiot[1] = {&ui_img_bgiot4_png};
const lv_img_dsc_t * ui_imgset_btn[1] = {&ui_img_btn2_png};
const lv_img_dsc_t * ui_imgset_iconalarm[1] = {&ui_img_iconalarm1_png};
const lv_img_dsc_t * ui_imgset_iconclock[1] = {&ui_img_iconclock1_png};
const lv_img_dsc_t * ui_imgset_iconexit[1] = {&ui_img_iconexit1_png};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_BtnMenu(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_LoginScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_LoginScreen_screen_init);
    }
}
void ui_event_PinCodeTextArea(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_FOCUSED) {
        _ui_flag_modify(ui_LOGINFAILED, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_SENDNEWPW, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_KBLogin, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
    if(event_code == LV_EVENT_DEFOCUSED) {
        _ui_flag_modify(ui_KBLogin, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}
void ui_event_LoginButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        LoginFunc(e);
        lv_textarea_set_text(ui_PinCodeTextArea, "");
	    lv_textarea_set_placeholder_text(ui_PinCodeTextArea, "Password....");	
    }
}
void ui_event_TextForgotPWUserLogin(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        ForgotUserLogin(e);
        //lv_obj_set_style_text_color(ui_TextForgotPWUserLogin, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_PRESSED);
    }
}
void ui_event_KBLogin(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_READY) {
        _ui_flag_modify(ui_KBLogin, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_state_modify(ui_PinCodeTextArea, LV_STATE_FOCUSED, _UI_MODIFY_STATE_REMOVE);
    }
    if(event_code == LV_EVENT_CANCEL) {
        _ui_flag_modify(ui_KBLogin, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}
void ui_event_BTNExitMN(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_HomeScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_HomeScreen_screen_init);
    }
}
void ui_event_BTNSettingUser(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_SettingUserScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_SettingUserScreen_screen_init);
    }
}
void ui_event_BTNRoom(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_LivingRoomScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_LivingRoomScreen_screen_init);
    }
}
void ui_event_BTNSettingTime(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_SettingTimeScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_SettingTimeScreen_screen_init);
    }
}
void ui_event_TextCurrentPW(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_FOCUSED) {
        _ui_flag_modify(ui_KBSetPW, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_keyboard_set_target(ui_KBSetPW,  ui_TextCurrentPW);
        _ui_flag_modify(ui_TextWrongPW, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_NotifySuccsess, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
    if(event_code == LV_EVENT_DEFOCUSED) {
        _ui_flag_modify(ui_KBSetPW, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}
void ui_event_TextNewPW(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_FOCUSED) {
        _ui_flag_modify(ui_KBSetPW, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_flag_modify(ui_TextCurrentPW, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_basic_set_property(ui_TextNewPW, _UI_BASIC_PROPERTY_POSITION_Y,  -10);
        _ui_keyboard_set_target(ui_KBSetPW,  ui_TextNewPW);
    }
    if(event_code == LV_EVENT_DEFOCUSED) {
        _ui_flag_modify(ui_KBSetPW, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_TextCurrentPW, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_basic_set_property(ui_TextNewPW, _UI_BASIC_PROPERTY_POSITION_Y,  50);
    }
}
void ui_event_BTNSaveChangeSTUser(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        SaveChangePWFunc(e);
//        _ui_screen_change(&ui_MenuScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_MenuScreen_screen_init);
        _ui_flag_modify( ui_NotifySuccsess, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        lv_textarea_set_text(ui_TextCurrentPW, "");
	    lv_textarea_set_placeholder_text(ui_TextCurrentPW, "Current Password.......");
	    lv_textarea_set_text(ui_TextNewPW, "");
	    lv_textarea_set_placeholder_text(ui_TextNewPW, "New Password.......");
    }
}
void ui_event_KBSetPW(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_READY) {
        _ui_flag_modify(ui_KBSetPW, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_basic_set_property(ui_TextNewPW, _UI_BASIC_PROPERTY_POSITION_Y,  50);
        _ui_flag_modify(ui_TextCurrentPW, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_state_modify(ui_TextNewPW, LV_STATE_FOCUSED, _UI_MODIFY_STATE_REMOVE);
        _ui_state_modify(ui_TextCurrentPW, LV_STATE_FOCUSED, _UI_MODIFY_STATE_REMOVE);
    }
    if(event_code == LV_EVENT_CANCEL) {
        _ui_flag_modify(ui_KBSetPW, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_TextCurrentPW, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_basic_set_property(ui_TextCurrentPW, _UI_BASIC_PROPERTY_POSITION_Y,  70);
    }
}
void ui_event_TextSetYear(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_FOCUSED) {
        _ui_keyboard_set_target(ui_KeyboardSetYear,  ui_TextSetYear);
        _ui_flag_modify(ui_KeyboardSetYear, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
    if(event_code == LV_EVENT_DEFOCUSED) {
        _ui_flag_modify(ui_KeyboardSetYear, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}
void ui_event_BTNBackToMenuSTTime(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        BTNSaveExitSTTime(e);
        lv_roller_set_selected(ui_RLSetHour, 00, true);
     	lv_roller_set_selected(ui_RLSetMinute, 00, true);
  	 	lv_roller_set_selected(ui_RLSetDate, 00, true);
     	lv_roller_set_selected(ui_RLSetMonth, 00, true);
     	lv_textarea_set_text(ui_TextSetYear, "");
     	lv_textarea_set_placeholder_text(ui_TextSetYear, "Type Year");
    }
}
void ui_event_BTNBackToMenuSTTime1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_MenuScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_MenuScreen_screen_init);
    }
}

void ui_event_KeyboardSetYear(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_READY) {
        _ui_state_modify(ui_TextSetYear, LV_STATE_FOCUSED, _UI_MODIFY_STATE_REMOVE);
        _ui_flag_modify(ui_KeyboardSetYear, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
    if(event_code == LV_EVENT_CANCEL) {
        _ui_flag_modify(ui_KeyboardSetYear, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_TextSetYear, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}
void ui_event_LivingRoomScreen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_KitchenRoomScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_KitchenRoomScreen_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_FarmScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_FarmScreen_screen_init);
    }
}
void ui_event_SwitchAuto(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        SWAUTOLVRON(e);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        SWAUTOLVROFF(e);
    }
}
void ui_event_SwitchDevice1LVR(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        SWDVC1LVRON(e);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        SWDVC1LVROFF(e);
    }
}
void ui_event_SwitchDevice2LVR(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        SWDVC2LVRON(e);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        SWDVC2LVROFF(e);
    }
}
void ui_event_BTNBackToMenuLVR(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_MenuScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_MenuScreen_screen_init);
    }
}
void ui_event_KitchenRoomScreen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_FarmScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_FarmScreen_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_LivingRoomScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_LivingRoomScreen_screen_init);
    }
}
void ui_event_BTNBackToMenuKCR(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_MenuScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_MenuScreen_screen_init);
    }
}
void ui_event_FarmScreen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_LivingRoomScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_LivingRoomScreen_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_KitchenRoomScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_KitchenRoomScreen_screen_init);
    }
}
void ui_event_SwitchDevice1FARM(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        StageWaterPumpON(e);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        StageWaterPumpOFF(e);
    }
}
void ui_event_SwitchDevice2FARM(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        StageTimerON(e);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        StageTimerOFF(e);
    }
}
void ui_event_BtnTimerFarm(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        SaveTimeTimer(e);
    }
}
void ui_event_BTNBackToMenuFarm(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_MenuScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_MenuScreen_screen_init);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_HomeScreen_screen_init();
    ui_LoginScreen_screen_init();
    ui_MenuScreen_screen_init();
    ui_SettingUserScreen_screen_init();
    ui_SettingTimeScreen_screen_init();
    ui_LivingRoomScreen_screen_init();
    ui_KitchenRoomScreen_screen_init();
    ui_FarmScreen_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_HomeScreen);
}
