// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: TESTFN4

#include "../ui.h"

void ui_MenuScreen_screen_init(void)
{
    ui_MenuScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_MenuScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_MenuScreen, &ui_img_bg2_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TitleMenu = lv_label_create(ui_MenuScreen);
    lv_obj_set_width(ui_TitleMenu, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TitleMenu, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TitleMenu, 30);
    lv_obj_set_y(ui_TitleMenu, 10);
    lv_label_set_text(ui_TitleMenu, "Main menu");
    lv_obj_set_style_text_color(ui_TitleMenu, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TitleMenu, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TitleMenu, &ui_font_H1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BTNExitMN = lv_btn_create(ui_MenuScreen);
    lv_obj_set_width(ui_BTNExitMN, 122);
    lv_obj_set_height(ui_BTNExitMN, 117);
    lv_obj_set_x(ui_BTNExitMN, -80);
    lv_obj_set_y(ui_BTNExitMN, -20);
    lv_obj_set_align(ui_BTNExitMN, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_add_flag(ui_BTNExitMN, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BTNExitMN, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BTNExitMN, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BTNExitMN, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_BTNExitMN, &ui_img_btn2_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_BTNExitMN, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_BTNExitMN, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_BTNExitMN, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_BTNExitMN, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_BTNExitMN, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BTNExitMN, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_BTNExitMN, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_IcExitMenu = lv_img_create(ui_BTNExitMN);
    lv_img_set_src(ui_IcExitMenu, &ui_img_iconexit1_png);
    lv_obj_set_x(ui_IcExitMenu, 0);
    lv_obj_set_y(ui_IcExitMenu, -15);
    lv_obj_set_align(ui_IcExitMenu, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_IcExitMenu, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_IcExitMenu, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TextBTNExit = lv_label_create(ui_BTNExitMN);
    lv_obj_set_width(ui_TextBTNExit, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TextBTNExit, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TextBTNExit, -18);
    lv_obj_set_y(ui_TextBTNExit, -13);
    lv_obj_set_align(ui_TextBTNExit, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_TextBTNExit, "Exit");
    lv_obj_set_style_text_font(ui_TextBTNExit, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BTNSettingUser = lv_btn_create(ui_MenuScreen);
    lv_obj_set_width(ui_BTNSettingUser, 122);
    lv_obj_set_height(ui_BTNSettingUser, 117);
    lv_obj_set_x(ui_BTNSettingUser, 70);
    lv_obj_set_y(ui_BTNSettingUser, -20);
    lv_obj_set_align(ui_BTNSettingUser, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_add_flag(ui_BTNSettingUser, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BTNSettingUser, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BTNSettingUser, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BTNSettingUser, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_BTNSettingUser, &ui_img_btn2_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_BTNSettingUser, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_BTNSettingUser, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_BTNSettingUser, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_BTNSettingUser, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_BTNSettingUser, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BTNSettingUser, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_BTNSettingUser, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_IcSTuserMenu = lv_img_create(ui_BTNSettingUser);
    lv_img_set_src(ui_IcSTuserMenu, &ui_img_icon_settings_png);
    lv_obj_set_width(ui_IcSTuserMenu, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_IcSTuserMenu, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_IcSTuserMenu, 0);
    lv_obj_set_y(ui_IcSTuserMenu, -15);
    lv_obj_set_align(ui_IcSTuserMenu, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_IcSTuserMenu, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_IcSTuserMenu, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TextBTNSTuser1 = lv_label_create(ui_BTNSettingUser);
    lv_obj_set_width(ui_TextBTNSTuser1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TextBTNSTuser1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TextBTNSTuser1, 0);
    lv_obj_set_y(ui_TextBTNSTuser1, -15);
    lv_obj_set_align(ui_TextBTNSTuser1, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_TextBTNSTuser1, "Setting\n  User");

    ui_BTNRoom = lv_btn_create(ui_MenuScreen);
    lv_obj_set_width(ui_BTNRoom, 122);
    lv_obj_set_height(ui_BTNRoom, 117);
    lv_obj_set_x(ui_BTNRoom, -80);
    lv_obj_set_y(ui_BTNRoom, 60);
    lv_obj_set_align(ui_BTNRoom, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_BTNRoom, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BTNRoom, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BTNRoom, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BTNRoom, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_BTNRoom, &ui_img_btn2_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_BTNRoom, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_BTNRoom, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_BTNRoom, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_BTNRoom, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_BTNRoom, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BTNRoom, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_BTNRoom, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_IcRoomMenu = lv_img_create(ui_BTNRoom);
    lv_img_set_src(ui_IcRoomMenu, &ui_img_iconhome_png);
    lv_obj_set_x(ui_IcRoomMenu, 0);
    lv_obj_set_y(ui_IcRoomMenu, -15);
    lv_obj_set_align(ui_IcRoomMenu, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_IcRoomMenu, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_IcRoomMenu, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TextBTNRoom = lv_label_create(ui_BTNRoom);
    lv_obj_set_width(ui_TextBTNRoom, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TextBTNRoom, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TextBTNRoom, -5);
    lv_obj_set_y(ui_TextBTNRoom, -12);
    lv_obj_set_align(ui_TextBTNRoom, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_TextBTNRoom, "Room");
    lv_obj_set_style_text_font(ui_TextBTNRoom, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BTNSettingTime = lv_btn_create(ui_MenuScreen);
    lv_obj_set_width(ui_BTNSettingTime, 122);
    lv_obj_set_height(ui_BTNSettingTime, 117);
    lv_obj_set_x(ui_BTNSettingTime, 70);
    lv_obj_set_y(ui_BTNSettingTime, 60);
    lv_obj_add_flag(ui_BTNSettingTime, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BTNSettingTime, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BTNSettingTime, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BTNSettingTime, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_BTNSettingTime, &ui_img_btn2_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_BTNSettingTime, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_BTNSettingTime, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_BTNSettingTime, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_BTNSettingTime, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_BTNSettingTime, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BTNSettingTime, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_BTNSettingTime, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_IcSTTimeMenu = lv_img_create(ui_BTNSettingTime);
    lv_img_set_src(ui_IcSTTimeMenu, &ui_img_iconclock1_png);
    lv_obj_set_width(ui_IcSTTimeMenu, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_IcSTTimeMenu, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_IcSTTimeMenu, 0);
    lv_obj_set_y(ui_IcSTTimeMenu, -15);
    lv_obj_set_align(ui_IcSTTimeMenu, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_IcSTTimeMenu, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_IcSTTimeMenu, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TextBTNSTTime1 = lv_label_create(ui_BTNSettingTime);
    lv_obj_set_width(ui_TextBTNSTTime1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TextBTNSTTime1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TextBTNSTTime1, -10);
    lv_obj_set_y(ui_TextBTNSTTime1, -15);
    lv_obj_set_align(ui_TextBTNSTTime1, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_TextBTNSTTime1, " Set\nTime");

    lv_obj_add_event_cb(ui_BTNExitMN, ui_event_BTNExitMN, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BTNSettingUser, ui_event_BTNSettingUser, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BTNRoom, ui_event_BTNRoom, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BTNSettingTime, ui_event_BTNSettingTime, LV_EVENT_ALL, NULL);

}
