// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: TESTFN4

#include "../ui.h"

void ui_SettingUserScreen_screen_init(void)
{
    ui_SettingUserScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_SettingUserScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_SettingUserScreen, &ui_img_bg2_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TitleSettingUser = lv_label_create(ui_SettingUserScreen);
    lv_obj_set_width(ui_TitleSettingUser, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TitleSettingUser, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TitleSettingUser, 30);
    lv_obj_set_y(ui_TitleSettingUser, 10);
    lv_label_set_text(ui_TitleSettingUser, "Setting User");
    lv_obj_set_style_text_color(ui_TitleSettingUser, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TitleSettingUser, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TitleSettingUser, &ui_font_H1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TitleEditPW = lv_label_create(ui_SettingUserScreen);
    lv_obj_set_width(ui_TitleEditPW, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TitleEditPW, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TitleEditPW, 0);
    lv_obj_set_y(ui_TitleEditPW, -80);
    lv_obj_set_align(ui_TitleEditPW, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TitleEditPW, "Change Password");
    lv_obj_set_style_text_color(ui_TitleEditPW, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TitleEditPW, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TitleEditPW, &ui_font_Subtitle, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TextCurrentPW = lv_textarea_create(ui_SettingUserScreen);
    lv_obj_set_width(ui_TextCurrentPW, 300);
    lv_obj_set_height(ui_TextCurrentPW, LV_SIZE_CONTENT);    /// 40
    lv_obj_set_x(ui_TextCurrentPW, 0);
    lv_obj_set_y(ui_TextCurrentPW, -10);
    lv_obj_set_align(ui_TextCurrentPW, LV_ALIGN_CENTER);
    if("0123456789" == "") lv_textarea_set_accepted_chars(ui_TextCurrentPW, NULL);
    else lv_textarea_set_accepted_chars(ui_TextCurrentPW, "0123456789");
    lv_textarea_set_max_length(ui_TextCurrentPW, 6);
    lv_textarea_set_placeholder_text(ui_TextCurrentPW, "Current Password.......");
    lv_textarea_set_one_line(ui_TextCurrentPW, true);
    lv_textarea_set_password_mode(ui_TextCurrentPW, true);



    ui_TextNewPW = lv_textarea_create(ui_SettingUserScreen);
    lv_obj_set_width(ui_TextNewPW, 300);
    lv_obj_set_height(ui_TextNewPW, LV_SIZE_CONTENT);    /// 40
    lv_obj_set_x(ui_TextNewPW, 0);
    lv_obj_set_y(ui_TextNewPW, 50);
    lv_obj_set_align(ui_TextNewPW, LV_ALIGN_CENTER);
    if("0123456789" == "") lv_textarea_set_accepted_chars(ui_TextNewPW, NULL);
    else lv_textarea_set_accepted_chars(ui_TextNewPW, "0123456789");
    lv_textarea_set_max_length(ui_TextNewPW, 6);
    lv_textarea_set_placeholder_text(ui_TextNewPW, "New Password.......");
    lv_textarea_set_one_line(ui_TextNewPW, true);
    lv_textarea_set_password_mode(ui_TextNewPW, true);

//    ui_TextForgotPW = lv_label_create(ui_SettingUserScreen);
//    lv_obj_set_width(ui_TextForgotPW, LV_SIZE_CONTENT);   /// 1
//    lv_obj_set_height(ui_TextForgotPW, LV_SIZE_CONTENT);    /// 1
//    lv_obj_set_x(ui_TextForgotPW, -92);
//    lv_obj_set_y(ui_TextForgotPW, -71);
//    lv_obj_set_align(ui_TextForgotPW, LV_ALIGN_BOTTOM_RIGHT);
//    lv_label_set_text(ui_TextForgotPW, "Forgot Password.......");
//    lv_obj_add_state(ui_TextForgotPW, LV_STATE_PRESSED);       /// States
//    lv_obj_add_flag(ui_TextForgotPW, LV_OBJ_FLAG_CLICKABLE);     /// Flags
//    lv_obj_set_style_text_color(ui_TextForgotPW, lv_color_hex(0x2F3FEC), LV_PART_MAIN | LV_STATE_DEFAULT);
//    lv_obj_set_style_text_opa(ui_TextForgotPW, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
//    lv_obj_set_style_text_decor(ui_TextForgotPW, LV_TEXT_DECOR_UNDERLINE, LV_PART_MAIN | LV_STATE_DEFAULT);
//    lv_obj_set_style_text_font(ui_TextForgotPW, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);
//    lv_obj_set_style_text_color(ui_TextForgotPW, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_PRESSED);
//    lv_obj_set_style_text_opa(ui_TextForgotPW, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_BTNSaveChangeSTUser = lv_btn_create(ui_SettingUserScreen);
    lv_obj_set_width(ui_BTNSaveChangeSTUser, 130);
    lv_obj_set_height(ui_BTNSaveChangeSTUser, 50);
    lv_obj_set_x(ui_BTNSaveChangeSTUser, 0);
    lv_obj_set_y(ui_BTNSaveChangeSTUser, -10);
    lv_obj_set_align(ui_BTNSaveChangeSTUser, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_BTNSaveChangeSTUser, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BTNSaveChangeSTUser, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BTNSaveChangeSTUser, lv_color_hex(0x3A445C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BTNSaveChangeSTUser, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TextBTNSaveChangeSTUser = lv_label_create(ui_BTNSaveChangeSTUser);
    lv_obj_set_width(ui_TextBTNSaveChangeSTUser, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TextBTNSaveChangeSTUser, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_TextBTNSaveChangeSTUser, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TextBTNSaveChangeSTUser, "SAVE & Change");

    ui_KBSetPW = lv_keyboard_create(ui_SettingUserScreen);
    lv_keyboard_set_mode(ui_KBSetPW, LV_KEYBOARD_MODE_NUMBER);
    lv_obj_set_width(ui_KBSetPW, 480);
    lv_obj_set_height(ui_KBSetPW, 132);
    lv_obj_set_x(ui_KBSetPW, 0);
    lv_obj_set_y(ui_KBSetPW, -10);
    lv_obj_set_align(ui_KBSetPW, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_KBSetPW, LV_OBJ_FLAG_HIDDEN);     /// Flags

    ui_NotifySuccsess = lv_label_create(ui_SettingUserScreen);
    lv_obj_set_width(ui_NotifySuccsess, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_NotifySuccsess, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_NotifySuccsess, 0);
    lv_obj_set_y(ui_NotifySuccsess, -52);
    lv_obj_set_align(ui_NotifySuccsess, LV_ALIGN_CENTER);
    lv_label_set_text(ui_NotifySuccsess, "Succsess");
    lv_obj_add_flag(ui_NotifySuccsess, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_color(ui_NotifySuccsess, lv_color_hex(0x00FF17), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_NotifySuccsess, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TextWrongPW = lv_label_create(ui_SettingUserScreen);
    lv_obj_set_width(ui_TextWrongPW, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TextWrongPW, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TextWrongPW, 0);
    lv_obj_set_y(ui_TextWrongPW, -52);
    lv_obj_set_align(ui_TextWrongPW, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TextWrongPW, "Current Password is incorrect!");
    lv_obj_add_flag(ui_TextWrongPW, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_color(ui_TextWrongPW, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TextWrongPW, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_TextCurrentPW, ui_event_TextCurrentPW, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TextNewPW, ui_event_TextNewPW, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BTNSaveChangeSTUser, ui_event_BTNSaveChangeSTUser, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_KBSetPW, ui_event_KBSetPW, LV_EVENT_ALL, NULL);

}
