// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: TESTFN4

#include "../ui.h"

void ui_SettingTimeScreen_screen_init(void)
{
    ui_SettingTimeScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_SettingTimeScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_SettingTimeScreen, &ui_img_bg2_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_SettingTimeScreen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_SettingTimeScreen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_SettingTimeScreen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_SettingTimeScreen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TitleSettingTime = lv_label_create(ui_SettingTimeScreen);
    lv_obj_set_width(ui_TitleSettingTime, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TitleSettingTime, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TitleSettingTime, 30);
    lv_obj_set_y(ui_TitleSettingTime, 10);
    lv_label_set_text(ui_TitleSettingTime, "Setting Time");
    lv_obj_set_style_text_color(ui_TitleSettingTime, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TitleSettingTime, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TitleSettingTime, &ui_font_H1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TextSetYearr = lv_label_create(ui_SettingTimeScreen);
    lv_obj_set_width(ui_TextSetYearr, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TextSetYearr, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TextSetYearr, -60);
    lv_obj_set_y(ui_TextSetYearr, -90);
    lv_obj_set_align(ui_TextSetYearr, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_TextSetYearr, "Set Year");
    lv_obj_set_style_text_color(ui_TextSetYearr, lv_color_hex(0xD2DCF2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TextSetYearr, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TextSetYear = lv_textarea_create(ui_SettingTimeScreen);
    lv_obj_set_width(ui_TextSetYear, 88);
    lv_obj_set_height(ui_TextSetYear, LV_SIZE_CONTENT);    /// 42
    lv_obj_set_x(ui_TextSetYear, -45);
    lv_obj_set_y(ui_TextSetYear, -50);
    lv_obj_set_align(ui_TextSetYear, LV_ALIGN_RIGHT_MID);
    lv_textarea_set_placeholder_text(ui_TextSetYear, "Type Year");
    lv_textarea_set_one_line(ui_TextSetYear, true);



    ui_GRSetDate = lv_obj_create(ui_SettingTimeScreen);
    lv_obj_set_width(ui_GRSetDate, 100);
    lv_obj_set_height(ui_GRSetDate, 128);
    lv_obj_set_x(ui_GRSetDate, 30);
    lv_obj_set_y(ui_GRSetDate, -50);
    lv_obj_set_align(ui_GRSetDate, LV_ALIGN_LEFT_MID);
    lv_obj_clear_flag(ui_GRSetDate, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_GRSetDate, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_GRSetDate, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_GRSetDate, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_GRSetDate, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_GRSetDate, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BGSetDate = lv_img_create(ui_GRSetDate);
    lv_img_set_src(ui_BGSetDate, &ui_img_roller_bg_png);
    lv_obj_set_width(ui_BGSetDate, LV_SIZE_CONTENT);   /// 91
    lv_obj_set_height(ui_BGSetDate, LV_SIZE_CONTENT);    /// 90
    lv_obj_set_x(ui_BGSetDate, 0);
    lv_obj_set_y(ui_BGSetDate, 20);
    lv_obj_set_align(ui_BGSetDate, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BGSetDate, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_BGSetDate, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_RLSetDate = lv_roller_create(ui_GRSetDate);
    lv_roller_set_options(ui_RLSetDate,
                          "01\n02\n03\n04\n05\n06\n07\n08\n09\n10\n11\n12\n13\n14\n15\n16\n17\n18\n19\n20\n21\n22\n23\n24\n25\n26\n27\n28\n29\n30\n31",
                          LV_ROLLER_MODE_NORMAL);
    lv_obj_set_width(ui_RLSetDate, 71);
    lv_obj_set_height(ui_RLSetDate, 66);
    lv_obj_set_x(ui_RLSetDate, 0);
    lv_obj_set_y(ui_RLSetDate, 20);
    lv_obj_set_align(ui_RLSetDate, LV_ALIGN_CENTER);
    lv_obj_set_style_text_color(ui_RLSetDate, lv_color_hex(0x3F475E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_RLSetDate, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_RLSetDate, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_RLSetDate, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RLSetDate, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_RLSetDate, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_RLSetDate, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_RLSetDate, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(ui_RLSetDate, lv_color_hex(0xDBE6FF), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_RLSetDate, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_RLSetDate, &lv_font_montserrat_14, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_RLSetDate, lv_color_hex(0x3A445C), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RLSetDate, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_TextSetDate = lv_label_create(ui_GRSetDate);
    lv_obj_set_width(ui_TextSetDate, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TextSetDate, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_TextSetDate, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_TextSetDate, "Set Date");
    lv_obj_set_style_text_color(ui_TextSetDate, lv_color_hex(0xD2DCF2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TextSetDate, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_GRSetMonth = lv_obj_create(ui_SettingTimeScreen);
    lv_obj_set_width(ui_GRSetMonth, 100);
    lv_obj_set_height(ui_GRSetMonth, 128);
    lv_obj_set_x(ui_GRSetMonth, 0);
    lv_obj_set_y(ui_GRSetMonth, -50);
    lv_obj_set_align(ui_GRSetMonth, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_GRSetMonth, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_GRSetMonth, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_GRSetMonth, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_GRSetMonth, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_GRSetMonth, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_GRSetMonth, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BGSetMonth = lv_img_create(ui_GRSetMonth);
    lv_img_set_src(ui_BGSetMonth, &ui_img_roller_bg_png);
    lv_obj_set_width(ui_BGSetMonth, LV_SIZE_CONTENT);   /// 91
    lv_obj_set_height(ui_BGSetMonth, LV_SIZE_CONTENT);    /// 90
    lv_obj_set_x(ui_BGSetMonth, 0);
    lv_obj_set_y(ui_BGSetMonth, 20);
    lv_obj_set_align(ui_BGSetMonth, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BGSetMonth, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_BGSetMonth, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_RLSetMonth = lv_roller_create(ui_GRSetMonth);
    lv_roller_set_options(ui_RLSetMonth, "01\n02\n03\n04\n05\n06\n07\n08\n09\n10\n11\n12", LV_ROLLER_MODE_NORMAL);
    lv_obj_set_width(ui_RLSetMonth, 71);
    lv_obj_set_height(ui_RLSetMonth, 66);
    lv_obj_set_x(ui_RLSetMonth, 0);
    lv_obj_set_y(ui_RLSetMonth, 20);
    lv_obj_set_align(ui_RLSetMonth, LV_ALIGN_CENTER);
    lv_obj_set_style_text_color(ui_RLSetMonth, lv_color_hex(0x3F475E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_RLSetMonth, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_RLSetMonth, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_RLSetMonth, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RLSetMonth, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_RLSetMonth, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_RLSetMonth, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_RLSetMonth, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(ui_RLSetMonth, lv_color_hex(0xDBE6FF), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_RLSetMonth, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_RLSetMonth, &lv_font_montserrat_14, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_RLSetMonth, lv_color_hex(0x3A445C), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RLSetMonth, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_TextSetMonth = lv_label_create(ui_GRSetMonth);
    lv_obj_set_width(ui_TextSetMonth, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TextSetMonth, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_TextSetMonth, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_TextSetMonth, "Set Month");
    lv_obj_set_style_text_color(ui_TextSetMonth, lv_color_hex(0xD2DCF2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TextSetMonth, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_GRSetHour = lv_obj_create(ui_SettingTimeScreen);
    lv_obj_set_width(ui_GRSetHour, 100);
    lv_obj_set_height(ui_GRSetHour, 128);
    lv_obj_set_x(ui_GRSetHour, 30);
    lv_obj_set_y(ui_GRSetHour, -20);
    lv_obj_set_align(ui_GRSetHour, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_clear_flag(ui_GRSetHour, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_GRSetHour, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_GRSetHour, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_GRSetHour, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_GRSetHour, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_GRSetHour, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BGSetHour = lv_img_create(ui_GRSetHour);
    lv_img_set_src(ui_BGSetHour, &ui_img_roller_bg_png);
    lv_obj_set_width(ui_BGSetHour, LV_SIZE_CONTENT);   /// 91
    lv_obj_set_height(ui_BGSetHour, LV_SIZE_CONTENT);    /// 90
    lv_obj_set_x(ui_BGSetHour, 0);
    lv_obj_set_y(ui_BGSetHour, 20);
    lv_obj_set_align(ui_BGSetHour, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BGSetHour, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_BGSetHour, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_RLSetHour = lv_roller_create(ui_GRSetHour);
    lv_roller_set_options(ui_RLSetHour,
                          "00\n01\n02\n03\n04\n05\n06\n07\n08\n09\n10\n11\n12\n13\n14\n15\n16\n17\n18\n19\n20\n21\n22\n23",
                          LV_ROLLER_MODE_NORMAL);
    lv_obj_set_width(ui_RLSetHour, 71);
    lv_obj_set_height(ui_RLSetHour, 66);
    lv_obj_set_x(ui_RLSetHour, 0);
    lv_obj_set_y(ui_RLSetHour, 20);
    lv_obj_set_align(ui_RLSetHour, LV_ALIGN_CENTER);
    lv_obj_set_style_text_color(ui_RLSetHour, lv_color_hex(0x3F475E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_RLSetHour, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_RLSetHour, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_RLSetHour, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RLSetHour, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_RLSetHour, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_RLSetHour, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_RLSetHour, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(ui_RLSetHour, lv_color_hex(0xDBE6FF), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_RLSetHour, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_RLSetHour, &lv_font_montserrat_14, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_RLSetHour, lv_color_hex(0x3A445C), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RLSetHour, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_TextSetHour = lv_label_create(ui_GRSetHour);
    lv_obj_set_width(ui_TextSetHour, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TextSetHour, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_TextSetHour, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_TextSetHour, "Set Hour");
    lv_obj_set_style_text_color(ui_TextSetHour, lv_color_hex(0xD2DCF2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TextSetHour, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_GRSetMinute = lv_obj_create(ui_SettingTimeScreen);
    lv_obj_set_width(ui_GRSetMinute, 100);
    lv_obj_set_height(ui_GRSetMinute, 128);
    lv_obj_set_x(ui_GRSetMinute, 0);
    lv_obj_set_y(ui_GRSetMinute, -20);
    lv_obj_set_align(ui_GRSetMinute, LV_ALIGN_BOTTOM_MID);
    lv_obj_clear_flag(ui_GRSetMinute, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_GRSetMinute, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_GRSetMinute, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_GRSetMinute, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_GRSetMinute, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_GRSetMinute, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BGSetMinute = lv_img_create(ui_GRSetMinute);
    lv_img_set_src(ui_BGSetMinute, &ui_img_roller_bg_png);
    lv_obj_set_width(ui_BGSetMinute, LV_SIZE_CONTENT);   /// 91
    lv_obj_set_height(ui_BGSetMinute, LV_SIZE_CONTENT);    /// 90
    lv_obj_set_x(ui_BGSetMinute, 0);
    lv_obj_set_y(ui_BGSetMinute, 20);
    lv_obj_set_align(ui_BGSetMinute, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BGSetMinute, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_BGSetMinute, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_RLSetMinute = lv_roller_create(ui_GRSetMinute);
    lv_roller_set_options(ui_RLSetMinute,
                          "00\n01\n02\n03\n04\n05\n06\n07\n08\n09\n10\n11\n12\n13\n14\n15\n16\n17\n18\n19\n20\n21\n22\n23\n24\n25\n26\n27\n28\n29\n30\n31\n32\n33\n34\n35\n36\n37\n38\n39\n40\n41\n42\n43\n44\n45\n46\n47\n48\n49\n50\n51\n52\n53\n54\n55\n56\n57\n58\n59",
                          LV_ROLLER_MODE_NORMAL);
    lv_obj_set_width(ui_RLSetMinute, 71);
    lv_obj_set_height(ui_RLSetMinute, 66);
    lv_obj_set_x(ui_RLSetMinute, 0);
    lv_obj_set_y(ui_RLSetMinute, 20);
    lv_obj_set_align(ui_RLSetMinute, LV_ALIGN_CENTER);
    lv_obj_set_style_text_color(ui_RLSetMinute, lv_color_hex(0x3F475E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_RLSetMinute, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_RLSetMinute, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_RLSetMinute, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RLSetMinute, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_RLSetMinute, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_RLSetMinute, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_RLSetMinute, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(ui_RLSetMinute, lv_color_hex(0xDBE6FF), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_RLSetMinute, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_RLSetMinute, &lv_font_montserrat_14, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_RLSetMinute, lv_color_hex(0x3A445C), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RLSetMinute, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_TextSetMinute = lv_label_create(ui_GRSetMinute);
    lv_obj_set_width(ui_TextSetMinute, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TextSetMinute, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_TextSetMinute, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_TextSetMinute, "Set Minute");
    lv_obj_set_style_text_color(ui_TextSetMinute, lv_color_hex(0xD2DCF2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TextSetMinute, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BTNBackToMenuSTTime = lv_btn_create(ui_SettingTimeScreen);
    lv_obj_set_width(ui_BTNBackToMenuSTTime, 100);
    lv_obj_set_height(ui_BTNBackToMenuSTTime, 50);
    lv_obj_set_x(ui_BTNBackToMenuSTTime, 150);
    lv_obj_set_y(ui_BTNBackToMenuSTTime, 30);
    lv_obj_set_align(ui_BTNBackToMenuSTTime, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BTNBackToMenuSTTime, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BTNBackToMenuSTTime, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BTNBackToMenuSTTime, lv_color_hex(0x3A445C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BTNBackToMenuSTTime, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TextBTNBackToMenuSTTime = lv_label_create(ui_BTNBackToMenuSTTime);
    lv_obj_set_width(ui_TextBTNBackToMenuSTTime, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TextBTNBackToMenuSTTime, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_TextBTNBackToMenuSTTime, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TextBTNBackToMenuSTTime, "Save");
    
    /////////////////////////
    
    ui_BTNBackToMenuSTTime1 = lv_btn_create(ui_SettingTimeScreen);
    lv_obj_set_width(ui_BTNBackToMenuSTTime1, 100);
    lv_obj_set_height(ui_BTNBackToMenuSTTime1, 50);
    lv_obj_set_x(ui_BTNBackToMenuSTTime1, 150);
    lv_obj_set_y(ui_BTNBackToMenuSTTime1, 100);
    lv_obj_set_align(ui_BTNBackToMenuSTTime1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BTNBackToMenuSTTime1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BTNBackToMenuSTTime1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BTNBackToMenuSTTime1, lv_color_hex(0x3A445C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BTNBackToMenuSTTime1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TextBTNBackToMenuSTTime1 = lv_label_create(ui_BTNBackToMenuSTTime1);
    lv_obj_set_width(ui_TextBTNBackToMenuSTTime1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TextBTNBackToMenuSTTime1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_TextBTNBackToMenuSTTime1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TextBTNBackToMenuSTTime1, "Back");
    
    //////////////////////////////

    ui_KeyboardSetYear = lv_keyboard_create(ui_SettingTimeScreen);
    lv_keyboard_set_mode(ui_KeyboardSetYear, LV_KEYBOARD_MODE_NUMBER);
    lv_obj_set_width(ui_KeyboardSetYear, 379);
    lv_obj_set_height(ui_KeyboardSetYear, 165);
    lv_obj_set_x(ui_KeyboardSetYear, 0);
    lv_obj_set_y(ui_KeyboardSetYear, 66);
    lv_obj_set_align(ui_KeyboardSetYear, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_KeyboardSetYear, LV_OBJ_FLAG_HIDDEN);     /// Flags

    lv_obj_add_event_cb(ui_TextSetYear, ui_event_TextSetYear, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BTNBackToMenuSTTime, ui_event_BTNBackToMenuSTTime, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BTNBackToMenuSTTime1, ui_event_BTNBackToMenuSTTime1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_KeyboardSetYear, ui_event_KeyboardSetYear, LV_EVENT_ALL, NULL);

}
