// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: TESTFN4

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void LoginFunc(lv_event_t * e);
void ForgotUserLogin(lv_event_t * e);
void SaveChangePWFunc(lv_event_t * e);
void BTNSaveExitSTTime(lv_event_t * e);
void SWAUTOLVRON(lv_event_t * e);
void SWAUTOLVROFF(lv_event_t * e);
void SWDVC1LVRON(lv_event_t * e);
void SWDVC1LVROFF(lv_event_t * e);
void SWDVC2LVRON(lv_event_t * e);
void SWDVC2LVROFF(lv_event_t * e);
void StageWaterPumpON(lv_event_t * e);
void StageWaterPumpOFF(lv_event_t * e);
void StageTimerON(lv_event_t * e);
void StageTimerOFF(lv_event_t * e);
void SaveTimeTimer(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
