// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: TESTFN4

#include "../ui.h"

void ui_LoginScreen_screen_init(void)
{
    ui_LoginScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_LoginScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_LoginScreen, &ui_img_bg2_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PinCodeTextArea = lv_textarea_create(ui_LoginScreen);
    lv_obj_set_width(ui_PinCodeTextArea, 200);
    lv_obj_set_height(ui_PinCodeTextArea, LV_SIZE_CONTENT);    /// 40
    lv_obj_set_x(ui_PinCodeTextArea, 0);
    lv_obj_set_y(ui_PinCodeTextArea, -25);
    lv_obj_set_align(ui_PinCodeTextArea, LV_ALIGN_CENTER);
    if("0123456789" == "") lv_textarea_set_accepted_chars(ui_PinCodeTextArea, NULL);
    else lv_textarea_set_accepted_chars(ui_PinCodeTextArea, "0123456789");
    lv_textarea_set_max_length(ui_PinCodeTextArea, 6);
    lv_textarea_set_placeholder_text(ui_PinCodeTextArea, "Password....");
    lv_textarea_set_one_line(ui_PinCodeTextArea, true);
    lv_textarea_set_password_mode(ui_PinCodeTextArea, true);



    ui_TitleLogin = lv_label_create(ui_LoginScreen);
    lv_obj_set_width(ui_TitleLogin, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TitleLogin, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TitleLogin, 0);
    lv_obj_set_y(ui_TitleLogin, 40);
    lv_obj_set_align(ui_TitleLogin, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_TitleLogin, "User Login");
    lv_obj_set_style_text_color(ui_TitleLogin, lv_color_hex(0x14E8E6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TitleLogin, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TitleLogin, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LoginButton = lv_btn_create(ui_LoginScreen);
    lv_obj_set_width(ui_LoginButton, 120);
    lv_obj_set_height(ui_LoginButton, 50);
    lv_obj_set_x(ui_LoginButton, 0);
    lv_obj_set_y(ui_LoginButton, 70);
    lv_obj_set_align(ui_LoginButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_LoginButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_LoginButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_LoginButton, 40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_LoginButton, lv_color_hex(0x9C9D9C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LoginButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LoginText = lv_label_create(ui_LoginButton);
    lv_obj_set_width(ui_LoginText, LV_SIZE_CONTENT);   /// -868
    lv_obj_set_height(ui_LoginText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LoginText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LoginText, "Login");
    lv_obj_set_style_text_font(ui_LoginText, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LOGINFAILED = lv_label_create(ui_LoginScreen);
    lv_obj_set_width(ui_LOGINFAILED, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LOGINFAILED, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LOGINFAILED, 0);
    lv_obj_set_y(ui_LOGINFAILED, -60);
    lv_obj_set_align(ui_LOGINFAILED, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LOGINFAILED, "Password is incorrect!");
    lv_obj_add_flag(ui_LOGINFAILED, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_color(ui_LOGINFAILED, lv_color_hex(0xFD0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LOGINFAILED, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LOGINFAILED, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

	ui_TextForgotPWUserLogin = lv_label_create(ui_LoginScreen);
    lv_obj_set_width(ui_TextForgotPWUserLogin, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TextForgotPWUserLogin, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TextForgotPWUserLogin, -83);
    lv_obj_set_y(ui_TextForgotPWUserLogin, -144);
    lv_obj_set_align(ui_TextForgotPWUserLogin, LV_ALIGN_BOTTOM_RIGHT);
    lv_label_set_text(ui_TextForgotPWUserLogin, "Forgot Password.......");
    lv_obj_add_state(ui_TextForgotPWUserLogin, LV_STATE_PRESSED);       /// States
    lv_obj_add_flag(ui_TextForgotPWUserLogin, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_set_style_text_color(ui_TextForgotPWUserLogin, lv_color_hex(0x2F3FEC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TextForgotPWUserLogin, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_TextForgotPWUserLogin, LV_TEXT_DECOR_UNDERLINE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TextForgotPWUserLogin, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_TextForgotPWUserLogin, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_text_opa(ui_TextForgotPWUserLogin, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    
    ui_SENDNEWPW = lv_label_create(ui_LoginScreen);
    lv_obj_set_width(ui_SENDNEWPW, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SENDNEWPW, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SENDNEWPW, 0);
    lv_obj_set_y(ui_SENDNEWPW, -60);
    lv_obj_set_align(ui_SENDNEWPW, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SENDNEWPW, "Send New Password Success!");
    lv_obj_add_flag(ui_SENDNEWPW, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_color(ui_SENDNEWPW, lv_color_hex(0xFD0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SENDNEWPW, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SENDNEWPW, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    
    ui_KBLogin = lv_keyboard_create(ui_LoginScreen);
    lv_keyboard_set_mode(ui_KBLogin, LV_KEYBOARD_MODE_NUMBER);
    lv_obj_set_width(ui_KBLogin, 480);
    lv_obj_set_height(ui_KBLogin, 160);
    lv_obj_set_x(ui_KBLogin, 0);
    lv_obj_set_y(ui_KBLogin, 80);
    lv_obj_set_align(ui_KBLogin, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_KBLogin, LV_OBJ_FLAG_HIDDEN);     /// Flags

    lv_obj_add_event_cb(ui_PinCodeTextArea, ui_event_PinCodeTextArea, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_LoginButton, ui_event_LoginButton, LV_EVENT_ALL, NULL);
    lv_keyboard_set_textarea(ui_KBLogin, ui_PinCodeTextArea);
    lv_obj_add_event_cb(ui_KBLogin, ui_event_KBLogin, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TextForgotPWUserLogin, ui_event_TextForgotPWUserLogin, LV_EVENT_ALL, NULL);

}
