// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: TESTFN4

#include "../ui.h"

void ui_KitchenRoomScreen_screen_init(void)
{
    ui_KitchenRoomScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_KitchenRoomScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_KitchenRoomScreen, &ui_img_ktroombg_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BTNBackToMenuKCR = lv_btn_create(ui_KitchenRoomScreen);
    lv_obj_set_width(ui_BTNBackToMenuKCR, 100);
    lv_obj_set_height(ui_BTNBackToMenuKCR, 50);
    lv_obj_set_x(ui_BTNBackToMenuKCR, 151);
    lv_obj_set_y(ui_BTNBackToMenuKCR, 106);
    lv_obj_set_align(ui_BTNBackToMenuKCR, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BTNBackToMenuKCR, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BTNBackToMenuKCR, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BTNBackToMenuKCR, lv_color_hex(0x3A445C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BTNBackToMenuKCR, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TextBTNBackToMenuKCR = lv_label_create(ui_BTNBackToMenuKCR);
    lv_obj_set_width(ui_TextBTNBackToMenuKCR, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TextBTNBackToMenuKCR, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_TextBTNBackToMenuKCR, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TextBTNBackToMenuKCR, "BACK");

    ui_TextTitleKCRoom = lv_label_create(ui_KitchenRoomScreen);
    lv_obj_set_width(ui_TextTitleKCRoom, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TextTitleKCRoom, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TextTitleKCRoom, 0);
    lv_obj_set_y(ui_TextTitleKCRoom, 20);
    lv_obj_set_align(ui_TextTitleKCRoom, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_TextTitleKCRoom, "Kitchen Room");
    lv_obj_set_style_text_color(ui_TextTitleKCRoom, lv_color_hex(0x0D12BE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TextTitleKCRoom, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TextTitleKCRoom, &lv_font_montserrat_36, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_BTNBackToMenuKCR, ui_event_BTNBackToMenuKCR, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_KitchenRoomScreen, ui_event_KitchenRoomScreen, LV_EVENT_ALL, NULL);

}
