// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: TESTFN4

#ifndef _TESTFN4_UI_H
#define _TESTFN4_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_HomeScreen
void ui_HomeScreen_screen_init(void);
extern lv_obj_t * ui_HomeScreen;
extern lv_obj_t * ui_DateHome;
extern lv_obj_t * ui_DayOTWHome;
extern lv_obj_t * ui_DayHome;
extern lv_obj_t * ui_MonthNameHome;
extern lv_obj_t * ui_YearHome;
extern lv_obj_t * ui_HourHome;
extern lv_obj_t * ui_colon1;
extern lv_obj_t * ui_MinuteHome;
extern lv_obj_t * ui_SecondHome;
extern lv_obj_t * ui_colon2;
extern lv_obj_t * ui_SunHome;
extern lv_obj_t * ui_CloudHome;
void ui_event_BtnMenu(lv_event_t * e);
extern lv_obj_t * ui_BtnMenu;
extern lv_obj_t * ui_ImgBtnMenu;
///
extern lv_obj_t * ui_namedayweather;
extern lv_obj_t * ui_iconweather;
extern lv_obj_t * ui_tempminweather;
extern lv_obj_t * ui_tempminweather1;
extern lv_obj_t * ui_tempmaxweather;
extern lv_obj_t * ui_tempmaxweather1;
extern lv_obj_t * ui_humweather;
extern lv_obj_t * ui_humweather1;
extern lv_obj_t * ui_pressureweather;
extern lv_obj_t * ui_pressureweather1;
extern lv_obj_t * ui_windspeedweather;
extern lv_obj_t * ui_windspeedweather1;
extern lv_obj_t * ui_iconweather1;
extern lv_obj_t * ui_iconweather2;
extern lv_obj_t * ui_iconweather3;
extern lv_obj_t * ui_Connect1;
extern lv_obj_t * ui_Connect2;
extern lv_obj_t * ui_Connect3;
///
// SCREEN: ui_LoginScreen
void ui_LoginScreen_screen_init(void);
extern lv_obj_t * ui_LoginScreen;
void ui_event_PinCodeTextArea(lv_event_t * e);
extern lv_obj_t * ui_PinCodeTextArea;
extern lv_obj_t * ui_TitleLogin;
void ui_event_LoginButton(lv_event_t * e);
extern lv_obj_t * ui_LoginButton;
extern lv_obj_t * ui_LoginText;
extern lv_obj_t * ui_LOGINFAILED;
extern lv_obj_t * ui_SENDNEWPW;
void ui_event_TextForgotPWUserLogin(lv_event_t * e);
extern lv_obj_t * ui_TextForgotPWUserLogin;
void ui_event_KBLogin(lv_event_t * e);
extern lv_obj_t * ui_KBLogin;
// SCREEN: ui_MenuScreen
void ui_MenuScreen_screen_init(void);
extern lv_obj_t * ui_MenuScreen;
extern lv_obj_t * ui_TitleMenu;
void ui_event_BTNExitMN(lv_event_t * e);
extern lv_obj_t * ui_BTNExitMN;
extern lv_obj_t * ui_IcExitMenu;
extern lv_obj_t * ui_TextBTNExit;
void ui_event_BTNSettingUser(lv_event_t * e);
extern lv_obj_t * ui_BTNSettingUser;
extern lv_obj_t * ui_IcSTuserMenu;
extern lv_obj_t * ui_TextBTNSTuser1;
void ui_event_BTNRoom(lv_event_t * e);
extern lv_obj_t * ui_BTNRoom;
extern lv_obj_t * ui_IcRoomMenu;
extern lv_obj_t * ui_TextBTNRoom;
void ui_event_BTNSettingTime(lv_event_t * e);
extern lv_obj_t * ui_BTNSettingTime;
extern lv_obj_t * ui_IcSTTimeMenu;
extern lv_obj_t * ui_TextBTNSTTime1;
// SCREEN: ui_SettingUserScreen
void ui_SettingUserScreen_screen_init(void);
extern lv_obj_t * ui_SettingUserScreen;
extern lv_obj_t * ui_TitleSettingUser;
extern lv_obj_t * ui_TitleEditPW;
void ui_event_TextCurrentPW(lv_event_t * e);
extern lv_obj_t * ui_TextCurrentPW;
void ui_event_TextNewPW(lv_event_t * e);
extern lv_obj_t * ui_TextNewPW;
//extern lv_obj_t * ui_TextForgotPW;
void ui_event_BTNSaveChangeSTUser(lv_event_t * e);
extern lv_obj_t * ui_BTNSaveChangeSTUser;
extern lv_obj_t * ui_TextBTNSaveChangeSTUser;
void ui_event_KBSetPW(lv_event_t * e);
extern lv_obj_t * ui_KBSetPW;
extern lv_obj_t * ui_NotifySuccsess;
extern lv_obj_t * ui_TextWrongPW;
// SCREEN: ui_SettingTimeScreen
void ui_SettingTimeScreen_screen_init(void);
extern lv_obj_t * ui_SettingTimeScreen;
extern lv_obj_t * ui_TitleSettingTime;
extern lv_obj_t * ui_TextSetYearr;
void ui_event_TextSetYear(lv_event_t * e);
extern lv_obj_t * ui_TextSetYear;
extern lv_obj_t * ui_GRSetDate;
extern lv_obj_t * ui_BGSetDate;
extern lv_obj_t * ui_RLSetDate;
extern lv_obj_t * ui_TextSetDate;
extern lv_obj_t * ui_GRSetMonth;
extern lv_obj_t * ui_BGSetMonth;
extern lv_obj_t * ui_RLSetMonth;
extern lv_obj_t * ui_TextSetMonth;
extern lv_obj_t * ui_GRSetHour;
extern lv_obj_t * ui_BGSetHour;
extern lv_obj_t * ui_RLSetHour;
extern lv_obj_t * ui_TextSetHour;
extern lv_obj_t * ui_GRSetMinute;
extern lv_obj_t * ui_BGSetMinute;
extern lv_obj_t * ui_RLSetMinute;
extern lv_obj_t * ui_TextSetMinute;
void ui_event_BTNBackToMenuSTTime(lv_event_t * e);
extern lv_obj_t * ui_BTNBackToMenuSTTime;
extern lv_obj_t * ui_TextBTNBackToMenuSTTime;
void ui_event_BTNBackToMenuSTTime1(lv_event_t * e);
extern lv_obj_t * ui_BTNBackToMenuSTTime1;
extern lv_obj_t * ui_TextBTNBackToMenuSTTime1;
void ui_event_KeyboardSetYear(lv_event_t * e);
extern lv_obj_t * ui_KeyboardSetYear;
// SCREEN: ui_LivingRoomScreen
void ui_LivingRoomScreen_screen_init(void);
void ui_event_LivingRoomScreen(lv_event_t * e);
extern lv_obj_t * ui_LivingRoomScreen;
extern lv_obj_t * ui_TextTitleLVRoom;
extern lv_obj_t * ui_TextAutoLVR;
void ui_event_SwitchAuto(lv_event_t * e);
extern lv_obj_t * ui_SwitchAuto;
extern lv_obj_t * ui_ValueAndStatusLVR;
extern lv_obj_t * ui_TextTempLVR;
extern lv_obj_t * ui_ValTempLVR;
extern lv_obj_t * ui_CelsiusTempLVR;
extern lv_obj_t * ui_TextHumLVR;
extern lv_obj_t * ui_ValHumLVR;
extern lv_obj_t * ui_PercentHumLVR;
extern lv_obj_t * ui_TextCO2LVR;
extern lv_obj_t * ui_ValCO2LVR;
extern lv_obj_t * ui_PPMCO2LVR;
extern lv_obj_t * ui_TextTVOCLVR;
extern lv_obj_t * ui_ValTVOCLVR;
extern lv_obj_t * ui_PPBTVOCLVR;
extern lv_obj_t * ui_TextFireSSLVR;
extern lv_obj_t * ui_ValFireSSLVR;
extern lv_obj_t * ui_TextSmokeSSLVR;
extern lv_obj_t * ui_ValSmokeSSLVR;
extern lv_obj_t * ui_TextDevice1LVR;
void ui_event_SwitchDevice1LVR(lv_event_t * e);
extern lv_obj_t * ui_SwitchDevice1LVR;
extern lv_obj_t * ui_TextDevice2LVR;
void ui_event_SwitchDevice2LVR(lv_event_t * e);
extern lv_obj_t * ui_SwitchDevice2LVR;
void ui_event_BTNBackToMenuLVR(lv_event_t * e);
extern lv_obj_t * ui_BTNBackToMenuLVR;
extern lv_obj_t * ui_TextBTNBackToMenuLVR;
// SCREEN: ui_KitchenRoomScreen
void ui_KitchenRoomScreen_screen_init(void);
void ui_event_KitchenRoomScreen(lv_event_t * e);
extern lv_obj_t * ui_KitchenRoomScreen;
void ui_event_BTNBackToMenuKCR(lv_event_t * e);
extern lv_obj_t * ui_BTNBackToMenuKCR;
extern lv_obj_t * ui_TextBTNBackToMenuKCR;
extern lv_obj_t * ui_TextTitleKCRoom;
// SCREEN: ui_FarmScreen
void ui_FarmScreen_screen_init(void);
void ui_event_FarmScreen(lv_event_t * e);
extern lv_obj_t * ui_FarmScreen;
extern lv_obj_t * ui_TextTitleFarm;
extern lv_obj_t * ui_ValueAndStatusFarm;
extern lv_obj_t * ui_TextTempFarm;
extern lv_obj_t * ui_ValTempFarm;
extern lv_obj_t * ui_CelsiusTempFarm;
extern lv_obj_t * ui_TextHumFarm;
extern lv_obj_t * ui_ValHumFarm;
extern lv_obj_t * ui_PercentHumFarm;
extern lv_obj_t * ui_TextSoilFarm;
extern lv_obj_t * ui_ValSoilFarm;
extern lv_obj_t * ui_PercentSoilFarm;
extern lv_obj_t * ui_TextRainSSFarm;
extern lv_obj_t * ui_ValRainSSFarm;
extern lv_obj_t * ui_TextDeviceFarm;
void ui_event_SwitchDevice1FARM(lv_event_t * e);
extern lv_obj_t * ui_SwitchDevice1FARM;
extern lv_obj_t * ui_LabelTimerFarm;
void ui_event_SwitchDevice2FARM(lv_event_t * e);
extern lv_obj_t * ui_SwitchDevice2FARM;
extern lv_obj_t * ui_TimerFarm;
extern lv_obj_t * ui_TextTimerFarm;
extern lv_obj_t * ui_TextNotifTimerFarm;
extern lv_obj_t * ui_BGSetHourTimerFarm;
extern lv_obj_t * ui_TextSetHourTimerFarm;
extern lv_obj_t * ui_RLSetHourTimerFarm;
extern lv_obj_t * ui_TextSetMinuteTimerFarm;
extern lv_obj_t * ui_BGSetMinuteTimerFarm;
extern lv_obj_t * ui_RLSetMinuteTimerFarm;
void ui_event_BtnTimerFarm(lv_event_t * e);
extern lv_obj_t * ui_BtnTimerFarm;
extern lv_obj_t * ui_TextBTNTimerFarm;
void ui_event_BTNBackToMenuFarm(lv_event_t * e);
extern lv_obj_t * ui_BTNBackToMenuFarm;
extern lv_obj_t * ui_TextBTNBackToMenuFarm;
extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(ui_img_bgiot4_png);    // assets/bgIoT4.png
LV_IMG_DECLARE(ui_img_sun_png);    // assets/sun.png
LV_IMG_DECLARE(ui_img_clouds_png);    // assets/clouds.png
LV_IMG_DECLARE(ui_img_house_png);    // assets/house.png
///
LV_IMG_DECLARE(ui_img_weather_png);    // assets/weather.png
LV_IMG_DECLARE(ui_img_weather_cloud_png);    // assets/weather_cloud.png
LV_IMG_DECLARE(ui_img_weather_cloud_fog_png);    // assets/weather_cloud_fog.png
LV_IMG_DECLARE(ui_img_weather_sun_png);    // assets/weather_sun.png
///
LV_IMG_DECLARE(ui_img_bg2_png);    // assets/bg2.png
LV_IMG_DECLARE(ui_img_btn2_png);    // assets/btn2.png
LV_IMG_DECLARE(ui_img_iconexit1_png);    // assets/iconexit1.png
LV_IMG_DECLARE(ui_img_icon_settings_png);    // assets/icon_settings.png
LV_IMG_DECLARE(ui_img_iconhome_png);    // assets/IconHOME.png
LV_IMG_DECLARE(ui_img_iconclock1_png);    // assets/iconclock1.png
LV_IMG_DECLARE(ui_img_roller_bg_png);    // assets/roller_bg.png
LV_IMG_DECLARE(ui_img_lroombg_png);    // assets/LRoomBG.png
LV_IMG_DECLARE(ui_img_img_switch_bg_png);    // assets/img_switch_bg.png
LV_IMG_DECLARE(ui_img_ktroombg_png);    // assets/KTRoomBG.png
LV_IMG_DECLARE(ui_img_farmbg_png);    // assets/FarmBG.png
LV_IMG_DECLARE(ui_img_bg3_png);    // assets/bg3.png
LV_IMG_DECLARE(ui_img_bggg2_png);    // assets/bggg2.png
LV_IMG_DECLARE(ui_img_iconalarm1_png);    // assets/iconalarm1.png



LV_FONT_DECLARE(ui_font_Font1Date);
LV_FONT_DECLARE(ui_font_Font2);
LV_FONT_DECLARE(ui_font_Font3);
LV_FONT_DECLARE(ui_font_FontDay);
LV_FONT_DECLARE(ui_font_H1);
LV_FONT_DECLARE(ui_font_Subtitle);



void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
